import React, { useEffect, useState } from 'react';
import {View, StyleSheet, KeyboardAvoidingView, Platform, ActivityIndicator, ScrollView} from 'react-native';
import { Text, TextInput, Button, useTheme } from 'react-native-paper';
import { useDispatch, useSelector } from 'react-redux';
import { setNewStoreHandle } from '../../store/newStoreSlice';
import { useRouter } from 'expo-router';
import axiosClient from '../../api/client';
import LogoIconWithName from "../../components/LogoIconWithName";

export default function StoreHandleScreen() {
    const theme = useTheme();
    const dispatch = useDispatch();
    const router = useRouter();

    const storeName = useSelector((state) => state.newStore.storeName);
    const existingHandle = useSelector((state) => state.newStore.storeHandle);

    const [localHandle, setLocalHandle] = useState(existingHandle || '');
    const [error, setError] = useState('');
    const [checking, setChecking] = useState(false);

    useEffect(() => {
        console.log('Store name:', storeName);
        console.log('Existing handle:', existingHandle);
        if (storeName.trim()) {
            fetchAutogeneratedHandle();
        }
    }, [storeName]);

    const fetchAutogeneratedHandle = async () => {
        try {
            const res = await axiosClient.post('/autogenerateStoreHandle', {
                storeName,
            });
            console.log('Fetched handle:', res.data);
            setLocalHandle(res.data.storeHandle);
            dispatch(setNewStoreHandle(res.data.storeHandle));
        } catch (err) {
            console.error('Failed to fetch handle:', err);
        }
    };

    const checkHandleAvailability = async () => {
        if (!localHandle.trim()) {
            setError('Handle is required');
            return false;
        }

        setChecking(true);
        try {
            const res = await axiosClient.post('/checkStoreHandleAvailability', {
                storeHandle: localHandle.trim(),
            });

            if (!res.data.available) {
                setError('Handle is already taken');
                return false;
            }

            setError('');
            return true;
        } catch (err) {
            console.error('Error checking handle:', err);
            setError('Failed to check availability');
            return false;
        } finally {
            setChecking(false);
        }
    };

    const handleNext = async () => {
        const isAvailable = await checkHandleAvailability();
        if (!isAvailable) return;

        dispatch(setNewStoreHandle(localHandle.trim()));
        router.push('/CreateStore/StoreDescription');
    };

    return (
        <KeyboardAvoidingView
            behavior={Platform.OS === 'ios' ? 'padding' : undefined}
            style={{ flex: 1, backgroundColor: 'white' }}
        >
            <ScrollView contentContainerStyle={styles.container}   keyboardShouldPersistTaps="handled">
                <View style={{ flex: 1, justifyContent: 'center' }}>
                    <LogoIconWithName style={{alignSelf: 'center', marginBottom: 24}}/>
                <Text variant="titleLarge" style={styles.heading}>
                    Store Handle
                </Text>

                <Text variant="bodyMedium" style={{ marginBottom: 12 }}>
                    This will be your store's public URL identifier.
                </Text>

                <TextInput
                    label="Store Handle"
                    mode="outlined"
                    value={localHandle}
                    onChangeText={( text) => {
                        setLocalHandle(text);
                        setError('');
                    }}
                    style={styles.input}
                    autoCapitalize="none"
                    error={!!error}
                />

                {error ? (
                    <Text style={{ color: theme.colors.error, marginBottom: 8 }}>
                        {error}
                    </Text>
                ) : null}

                <View style={{display: 'flex', alignSelf: 'center', justifyContent: 'center'}}>
                <Button
                    mode="contained"
                    onPress={handleNext}
                    disabled={checking}
                    style={{ borderRadius: 8 }}
                >
                    {checking ? (
                        <ActivityIndicator animating color="white" size="small" />
                    ) : (
                        'Next'
                    )}
                </Button>
                </View>
                </View>
            </ScrollView>
        </KeyboardAvoidingView>
    );
}

const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        padding: 20,
        justifyContent: 'center',
        backgroundColor: 'white',
    },
    heading: {
        marginBottom: 16,
        textAlign: 'center',
    },
    input: {
        marginBottom: 16,
        backgroundColor: 'white',
    },
});