import React, { useEffect, useState } from 'react';
import {View, StyleSheet, KeyboardAvoidingView, Platform, ActivityIndicator, ScrollView} from 'react-native';
import { Text, TextInput, Button, useTheme } from 'react-native-paper';
import { useDispatch, useSelector } from 'react-redux';
import { setNewStoreHandle } from '../../store/newStoreSlice';
import { useRouter } from 'expo-router';
import { getAxiosClient } from '../../api/client';
import LogoIconWithName from "../../components/LogoIconWithName";

const IS_WEB = Platform.OS === 'web';
export default function StoreHandleScreen() {
    const theme = useTheme();
    const dispatch = useDispatch();
    const router = useRouter();
    const axiosClient = getAxiosClient();
    const storeName = useSelector((state) => state.newStore.storeName);
    const existingHandle = useSelector((state) => state.newStore.storeHandle);

    const [localHandle, setLocalHandle] = useState(existingHandle || '');
    const [error, setError] = useState('');
    const [checking, setChecking] = useState(false);

    useEffect(() => {
        console.log('Store name:', storeName); // Kept original console.log
        console.log('Existing handle:', existingHandle); // Kept original console.log
        if (storeName && storeName.trim() && !existingHandle) { // Only fetch if no existing handle from redux
            fetchAutogeneratedHandle();
        } else if (existingHandle) {
            setLocalHandle(existingHandle); // Ensure local state is synced if existingHandle changes
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [storeName, existingHandle]); // Added existingHandle to dependency array if needed

    const fetchAutogeneratedHandle = async () => {
        if (!storeName || !storeName.trim()) return; // Extra guard
        // setChecking(true); // Optionally indicate loading for autogenerated handle
        try {
            const res = await axiosClient.post('/autogenerateStoreHandle', {
                storeName,
            });
            console.log('Fetched handle:', res.data); // Kept original console.log
            if (res.data && res.data.storeHandle) {
                setLocalHandle(res.data.storeHandle);
                // dispatch(setNewStoreHandle(res.data.storeHandle)); // Dispatching here might be premature, user might edit it. Dispatch on 'Next'.
            }
        } catch (err) {
            console.error('Failed to fetch handle:', err); // Kept original console.error
        } finally {
            // setChecking(false);
        }
    };

    const checkHandleAvailability = async () => {
        const trimmedHandle = localHandle.trim();
        if (!trimmedHandle) {
            setError('Store handle is required.');
            return false;
        }
        // Basic handle validation (e.g., no spaces, allowed characters) can be added here
        if (/\s/.test(trimmedHandle) || !/^[a-zA-Z0-9-]+$/.test(trimmedHandle)) {
            setError('Handle can only contain letters, numbers, and hyphens, with no spaces.');
            return false;
        }


        setChecking(true);
        setError(''); // Clear previous errors
        try {
            const res = await axiosClient.post('/checkStoreHandleAvailability', {
                storeHandle: trimmedHandle,
            });

            if (!res.data.available) {
                setError('This handle is already taken. Please try another.');
                return false;
            }
            return true; // Handle is available
        } catch (err) {
            console.error('Error checking handle:', err); // Kept original console.error
            setError('Failed to check handle availability. Please try again.');
            return false;
        } finally {
            setChecking(false);
        }
    };

    const handleNext = async () => {
        const isAvailable = await checkHandleAvailability();
        if (!isAvailable) return;

        dispatch(setNewStoreHandle(localHandle.trim()));
        router.push(IS_WEB ? '/create_store/store_description' : '/CreateStore/StoreDescription'); // Navigate to the next screen
    };

    const commonWrapperStyle = { flex: 1, backgroundColor: 'white' };

    const screenContent = (
        <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
            <View style={{ flex: 1, justifyContent: 'center', width: '100%'}}>
                <LogoIconWithName style={{alignSelf: 'center', marginBottom: 24}}/>
                <Text variant="titleLarge" style={styles.heading}>
                    Choose Your Store Handle
                </Text>

                <Text variant="bodyMedium" style={styles.subheading}>
                    This will be part of your store's unique web address (URL). E.g., www.rocketshop.in/<Text style={{fontWeight: 'bold'}}>{localHandle || 'yourhandle'}</Text>
                </Text>

                <TextInput
                    label="Store Handle (e.g., my-awesome-store)"
                    mode="outlined"
                    value={localHandle}
                    onChangeText={(text) => {
                        // Automatically convert to lowercase and replace spaces with hyphens, remove special chars
                        const formattedText = text.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
                        setLocalHandle(formattedText);
                        if (error) setError(''); // Clear error when user types
                    }}
                    style={styles.input}
                    autoCapitalize="none"
                    error={!!error}
                />

                {Boolean(error) && ( // Ensure error text is only shown if error string is not empty
                    <Text style={styles.errorText}>
                        {error}
                    </Text>
                )}

                <View style={{display: 'flex', alignSelf: 'center', justifyContent: 'center', marginTop: 24}}>
                    <Button
                        mode="contained"
                        onPress={handleNext}
                        disabled={checking || !localHandle.trim()} // Disable if checking or handle is empty
                        style={styles.button}
                        // contentStyle={{paddingVertical: 4}} // Add padding inside button
                    >
                        {checking ? (
                            <ActivityIndicator animating color="white" size="small" />
                        ) : (
                            'Next'
                        )}
                    </Button>
                </View>
            </View>
        </ScrollView>
    );

    if (Platform.OS === 'web') {
        return (
            <View style={commonWrapperStyle}>
                {screenContent}
            </View>
        );
    } else {
        return (
            <KeyboardAvoidingView
                behavior={Platform.OS === 'ios' ? 'padding' : undefined}
                style={commonWrapperStyle}
            >
                {screenContent}
            </KeyboardAvoidingView>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        padding: 20,
        justifyContent: 'center',
        backgroundColor: 'white',
        // Web-specific styles
        ...(Platform.OS === 'web' && {
            width: '100%',
            maxWidth: 550, // Adjusted max-width slightly for this form
            alignSelf: 'center',
        }),
    },
    heading: {
        marginBottom: 8, // Reduced margin
        textAlign: 'center',
    },
    subheading: {
        marginBottom: 20, // Increased margin
        textAlign: 'center',
        paddingHorizontal: 10, // Add some horizontal padding to subheading
        color: 'grey', // Subdued color for explanatory text
    },
    input: {
        marginBottom: 8, // Reduced margin, error text will take up space
        backgroundColor: 'white',
    },
    errorText: {
        color: 'red', // Directly use theme.colors.error if available from useTheme()
        marginBottom: 16,
        textAlign: 'center',
        minHeight: 20, // Reserve space for error text to prevent layout jumps
    },
    button: {
        borderRadius: 8,
        // width: '90%', // Make button wider
    }
});